### ISSUE TITLE
auth_on_register plugin

### ISSUE THREAD

**Issue by TestFirebaseLogin** [larshesel/vmq_elixir_plugin#5]
Hi sir,it not actually a bug,but im not able to connect via freenode/#vernemq or slack,https://slack-invite.vernemq.com/...so im opening it as an issue here(Sorry for it,but really need help).

I have implemented elixir plugin, following the repo...but i want to send sustom message on {:error, :message},but i went through the code https://github.com/erlio/vernemq/blob/a9b666ad042f493fc9cea32c06afac5241b4d0c9/apps/vmq_server/src/vmq_mqtt_fsm.erl on line 539,i realized for any other message than invalid_credentials it sends CONNACK_AUTH.

Any suggestions on how can i send mine custom message to connecting client,so he may know why he is not authenticated to connect to vernemq broker?

**Comment by larshesel** [comment]
The slack invite should work again.

Not sure what you mean by a custom message. MQTT 3.1.1 only specifies sending a few specific connect reasons (success, server_busy, invalid_credentials etc) with the CONNACK, not custom ones.

In MQTT v5.0 it will be possible to send reason strings together with reason codes to give more information to the client of what's going on.

**Comment by TestFirebaseLogin** [comment]
Sir,imagine i have a authentication setup ,that allows only 5 active clients,based on ur api key,which iam sending appended to clientid from mqtt client library, and seperating on broker side.

Now after checking in database,if limit of devices allowed is exceeded, can i tell the client ,the reason for not allowing connection.(Custom message)

**Comment by larshesel** [comment]
You cannot directly via MQTT v3.1.1 as I said.

The only option would be to allow the connection and then afterwards send the client an MQTT publish frame with the information and then disconnect the client. But that's IMHO a bad solution as this means between the CONNACK from the server clients could potentially publish/subscribe to messages. Otherwise you'd have to build logic to prevent them from this. This becomes complex.

I would consider if it is really important that the client knows why it was disconnected. In most cases it's enough to log the information so the VerneMQ operators know that a specific client was rejected due to rate-limiting issues.

Can I ask you to post any more questions on the slack channel instead? Thanks!

**Comment by TestFirebaseLogin** [comment]
Ok,thanks sir,i joined the slack channel,incase of nay doubts i will post there.Thanks for your time.
